export const jurisdictionsPayload = [
  {
    code: "cannada",
    name: "Cannada",
    regions: [{ code: "CA", name: "Canada" }],
    regulationNames: ["Common Principles"],
    rightsFulfilment: [
      {
        fulfillment: 45,
        rightCode: "cmn_delete",
        rightName: "Data Deletion",
      },
      { fulfillment: 45, rightCode: "cmn_access", rightName: "Data Access" },
      {
        fulfillment: 45,
        rightCode: "cmn_port",
        rightName: "Data Portability",
      },
      {
        fulfillment: 45,
        rightCode: "cmn_correction",
        rightName: "Data Correction",
      },
    ],
  },
  {
    code: "dsfdsfdsfdsfdsfd",
    name: "dsfdsfdsfdsfdsfd",
    regions: [{ code: "DZ", name: "Algeria" }],
  },
  {
    code: "france",
    name: "France",
    regions: [{ code: "FR", name: "France" }],
    regulationNames: ["ePrivacy", "GDPR"],
    rightsFulfilment: [
      {
        fulfillment: 90,
        rightCode: "gdpr_object",
        rightName: "Right to Object (GDPR)",
      },
      {
        fulfillment: 90,
        rightCode: "gdpr_access",
        rightName: "Right of Access (GDPR)",
      },
      {
        fulfillment: 90,
        rightCode: "gdpr_delete",
        rightName: "Right to Erasure (GDPR)",
      },
      {
        fulfillment: 90,
        rightCode: "gdpr_restrictprocessing",
        rightName: "Right to Restrict Processing (GDPR)",
      },
      {
        fulfillment: 90,
        rightCode: "gdpr_portability",
        rightName: "Right to Data Portability (GDPR)",
      },
      {
        fulfillment: 90,
        rightCode: "gdpr_rectification",
        rightName: "Right to Rectification (GDPR)",
      },
    ],
  },
  {
    code: "germany",
    name: "Germany",
    regions: [{ code: "DE", name: "Germany" }],
  },
  {
    code: "default",
    description:
      "This covers all regions not otherwise covered by a policy scope. vr",
    name: "Global Standard",
    regions: [
      { code: "AF", name: "Afghanistan" },
      { code: "AX", name: "Åland Islands" },
      { code: "US_AK", name: "Alaska" },
      { code: "AL", name: "Albania" },
      { code: "AS", name: "American Samoa" },
      { code: "AD", name: "Andorra" },
      { code: "AO", name: "Angola" },
      { code: "AI", name: "Anguilla" },
      { code: "AQ", name: "Antarctica" },
      { code: "AG", name: "Antigua and Barbuda" },
      { code: "AR", name: "Argentina" },
      { code: "US_AZ", name: "Arizona" },
      { code: "US_AR", name: "Arkansas" },
      { code: "AM", name: "Armenia" },
      { code: "AW", name: "Aruba" },
      { code: "AU", name: "Australia" },
      { code: "AT", name: "Austria" },
      { code: "AZ", name: "Azerbaijan" },
      { code: "BS", name: "Bahamas, The" },
      { code: "BS", name: "Bahamas, The" },
      { code: "BH", name: "Bahrain" },
      { code: "BD", name: "Bangladesh" },
      { code: "BB", name: "Barbados" },
      { code: "BY", name: "Belarus" },
      { code: "BE", name: "Belgium" },
      { code: "BZ", name: "Belize" },
      { code: "BJ", name: "Benin" },
      { code: "BM", name: "Bermuda" },
      { code: "BT", name: "Bhutan" },
      { code: "BO", name: "Bolivia" },
      { code: "BQ", name: "Bonaire" },
      { code: "BA", name: "Bosnia and Herzegovina" },
      { code: "BW", name: "Botswana" },
      { code: "BV", name: "Bouvet Island" },
      { code: "BR", name: "Brazil" },
      { code: "IO", name: "British Indian Ocean Territory" },
      { code: "BN", name: "Brunei" },
      { code: "BG", name: "Bulgaria" },
      { code: "BF", name: "Burkina Faso" },
      { code: "BI", name: "Burundi" },
      { code: "CV", name: "Cabo Verde" },
      { code: "KH", name: "Cambodia" },
      { code: "CM", name: "Cameroon" },
      { code: "KY", name: "Cayman Islands" },
      { code: "CF", name: "Central African Republic" },
      { code: "TD", name: "Chad" },
      { code: "CL", name: "Chile" },
      { code: "CN", name: "China" },
      { code: "HK", name: "China, Hong Kong Special Administrative Region" },
      { code: "MO", name: "China, Macao Special Administrative Region" },
      { code: "CX", name: "Christmas Island" },
      { code: "CC", name: "Cocos (Keeling) Islands" },
      { code: "CO", name: "Colombia" },
      { code: "US_CO", name: "Colorado" },
      { code: "KM", name: "Comoros" },
      { code: "CD", name: "Congo, Democratic Republic of the" },
      { code: "CG", name: "Congo, Republic of the" },
      { code: "CK", name: "Cook Islands" },
      { code: "CR", name: "Costa Rica" },
      { code: "CI", name: "Côte d’Ivoire" },
      { code: "HR", name: "Croatia" },
      { code: "CU", name: "Cuba" },
      { code: "CW", name: "Curaçao" },
      { code: "CY", name: "Cyprus" },
      { code: "CZ", name: "Czech Republic" },
      { code: "US_DE", name: "Delaware" },
      { code: "DK", name: "Denmark" },
      { code: "DJ", name: "Djibouti" },
      { code: "DM", name: "Dominica" },
      { code: "DO", name: "Dominican Republic" },
      { code: "EC", name: "Ecuador" },
      { code: "EG", name: "Egypt" },
      { code: "SV", name: "El Salvador" },
      { code: "GQ", name: "Equatorial Guinea" },
      { code: "ER", name: "Eritrea" },
      { code: "EE", name: "Estonia" },
      { code: "SZ", name: "Eswatini" },
      { code: "ET", name: "Ethiopia" },
      { code: "FK", name: "Falkland Islands" },
      { code: "FO", name: "Faroe Islands" },
      { code: "FJ", name: "Fiji" },
      { code: "FI", name: "Finland" },
      { code: "US_FL", name: "Florida" },
      { code: "GF", name: "French Guiana" },
      { code: "PF", name: "French Polynesia" },
      { code: "TF", name: "French Southern and Antarctic Lands" },
      { code: "GA", name: "Gabon" },
      { code: "GM", name: "Gambia, The" },
      { code: "GE", name: "Georgia" },
      { code: "US_GA", name: "Georgia" },
      { code: "GH", name: "Ghana" },
      { code: "GI", name: "Gibraltar" },
      { code: "GR", name: "Greece" },
      { code: "GL", name: "Greenland" },
      { code: "GD", name: "Grenada" },
      { code: "GP", name: "Guadeloupe" },
      { code: "GU", name: "Guam" },
      { code: "GT", name: "Guatemala" },
      { code: "GG", name: "Guernsey" },
      { code: "GN", name: "Guinea" },
      { code: "GW", name: "Guinea-Bissau" },
      { code: "GY", name: "Guyana" },
      { code: "HT", name: "Haiti" },
      { code: "US_HI", name: "Hawaii" },
      { code: "HM", name: "Heard Island and McDonald Islands" },
      { code: "VA", name: "Holy See" },
      { code: "HN", name: "Honduras" },
      { code: "HU", name: "Hungary" },
      { code: "IS", name: "Iceland" },
      { code: "US_ID", name: "Idaho" },
      { code: "US_IL", name: "Illinois" },
      { code: "IN", name: "India" },
      { code: "US_IN", name: "Indiana" },
      { code: "ID", name: "Indonesia" },
      { code: "US_IA", name: "Iowa" },
      { code: "IR", name: "Iran" },
      { code: "IQ", name: "Iraq" },
      { code: "IE", name: "Ireland" },
      { code: "IM", name: "Isle of Man" },
      { code: "IL", name: "Israel" },
      { code: "IT", name: "Italy" },
      { code: "JM", name: "Jamaica" },
      { code: "JP", name: "Japan" },
      { code: "JE", name: "Jersey" },
      { code: "JO", name: "Jordan" },
      { code: "US_KS", name: "Kansas" },
      { code: "KZ", name: "Kazakhstan" },
      { code: "US_KY", name: "Kentucky" },
      { code: "KE", name: "Kenya" },
      { code: "KI", name: "Kiribati" },
      { code: "KP", name: "Korea, North" },
      { code: "KR", name: "Korea, South" },
      { code: "KW", name: "Kuwait" },
      { code: "KG", name: "Kyrgyzstan" },
      { code: "LA", name: "Laos" },
      { code: "LV", name: "Latvia" },
      { code: "LB", name: "Lebanon" },
      { code: "LS", name: "Lesotho" },
      { code: "LR", name: "Liberia" },
      { code: "LY", name: "Libya" },
      { code: "LI", name: "Liechtenstein" },
      { code: "LT", name: "Lithuania" },
      { code: "US_LA", name: "Louisiana" },
      { code: "LU", name: "Luxembourg" },
      { code: "MG", name: "Madagascar" },
      { code: "MW", name: "Malawi" },
      { code: "MY", name: "Malaysia" },
      { code: "MV", name: "Maldives" },
      { code: "ML", name: "Mali" },
      { code: "MT", name: "Malta" },
      { code: "MH", name: "Marshall Islands" },
      { code: "MQ", name: "Martinique" },
      { code: "US_MD", name: "Maryland" },
      { code: "US_MA", name: "Massachusetts" },
      { code: "MR", name: "Mauritania" },
      { code: "MU", name: "Mauritius" },
      { code: "YT", name: "Mayotte" },
      { code: "MX", name: "Mexico" },
      { code: "US_MI", name: "Michigan" },
      { code: "FM", name: "Micronesia, Federated States of" },
      { code: "US_MN", name: "Minnesota" },
      { code: "US_MS", name: "Mississippi" },
      { code: "US_MO", name: "Missouri" },
      { code: "MD", name: "Moldova" },
      { code: "MC", name: "Monaco" },
      { code: "MN", name: "Mongolia" },
      { code: "US_MT", name: "Montana" },
      { code: "ME", name: "Montenegro" },
      { code: "MS", name: "Montserrat" },
      { code: "MA", name: "Morocco" },
      { code: "MZ", name: "Mozambique" },
      { code: "MM", name: "Myanmar" },
      { code: "NA", name: "Namibia" },
      { code: "NR", name: "Nauru" },
      { code: "NR", name: "Nauru" },
      { code: "US_NE", name: "Nebraska" },
      { code: "NP", name: "Nepal" },
      { code: "NL", name: "Netherlands" },
      { code: "US_NV", name: "Nevada" },
      { code: "NC", name: "New Caledonia" },
      { code: "US_NH", name: "New Hampshire" },
      { code: "US_NJ", name: "New Jersey" },
      { code: "US_NM", name: "New Mexico" },
      { code: "US_NY", name: "New York" },
      { code: "NZ", name: "New Zealand" },
      { code: "NI", name: "Nicaragua" },
      { code: "NE", name: "Niger" },
      { code: "NG", name: "Nigeria" },
      { code: "NF", name: "Norfolk Island" },
      { code: "US_NC", name: "North Carolina" },
      { code: "US_ND", name: "North Dakota" },
      { code: "MP", name: "Northern Mariana Islands" },
      { code: "MK", name: "North Macedonia" },
      { code: "NO", name: "Norway" },
      { code: "US_OH", name: "Ohio" },
      { code: "US_OK", name: "Oklahoma" },
      { code: "OM", name: "Oman" },
      { code: "US_OR", name: "Oregon" },
      { code: "PK", name: "Pakistan" },
      { code: "PW", name: "Palau" },
      { code: "PS", name: "Palestine, State of" },
      { code: "PA", name: "Panama" },
      { code: "PG", name: "Papua New Guinea" },
      { code: "PY", name: "Paraguay" },
      { code: "US_PA", name: "Pennsylvania" },
      { code: "PE", name: "Peru" },
      { code: "PH", name: "Philippines" },
      { code: "PN", name: "Pitcairn" },
      { code: "PL", name: "Poland" },
      { code: "PT", name: "Portugal" },
      { code: "PR", name: "Puerto Rico" },
      { code: "QA", name: "Qatar" },
      { code: "RE", name: "Réunion" },
      { code: "US_RI", name: "Rhode Island" },
      { code: "RO", name: "Romania" },
      { code: "RU", name: "Russia" },
      { code: "RW", name: "Rwanda" },
      { code: "BL", name: "Saint Barthélemy" },
      { code: "SH", name: "Saint Helena" },
      { code: "KN", name: "Saint Kitts and Nevis" },
      { code: "LC", name: "Saint Lucia" },
      { code: "MF", name: "Saint Martin" },
      { code: "PM", name: "Saint Pierre and Miquelon" },
      { code: "VC", name: "Saint Vincent and the Grenadines" },
      { code: "WS", name: "Samoa" },
      { code: "SM", name: "San Marino" },
      { code: "ST", name: "Sao Tome and Principe" },
      { code: "SA", name: "Saudi Arabia" },
      { code: "SN", name: "Senegal" },
      { code: "RS", name: "Serbia" },
      { code: "SC", name: "Seychelles" },
      { code: "SL", name: "Sierra Leone" },
      { code: "SG", name: "Singapore" },
      { code: "SX", name: "Sint Maarten" },
      { code: "SK", name: "Slovakia" },
      { code: "SI", name: "Slovenia" },
      { code: "SB", name: "Solomon Islands" },
      { code: "SO", name: "Somalia" },
      { code: "ZA", name: "South Africa" },
      { code: "US_SC", name: "South Carolina" },
      { code: "US_SD", name: "South Dakota" },
      { code: "GS", name: "South Georgia and the South Sandwich Islands" },
      { code: "SS", name: "South Sudan" },
      { code: "ES", name: "Spain" },
      { code: "LK", name: "Sri Lanka" },
      { code: "SR", name: "Suriname" },
      { code: "SJ", name: "Svalbard and Jan Mayen Islands" },
      { code: "SE", name: "Sweden" },
      { code: "CH", name: "Switzerland" },
      { code: "SY", name: "Syria" },
      { code: "TW", name: "Taiwan" },
      { code: "TJ", name: "Tajikistan" },
      { code: "TZ", name: "Tanzania" },
      { code: "US_TN", name: "Tennessee" },
      { code: "US_TX", name: "Texas" },
      { code: "TH", name: "Thailand" },
      { code: "TL", name: "Timor-Leste" },
      { code: "TG", name: "Togo" },
      { code: "TK", name: "Tokelau" },
      { code: "TO", name: "Tonga" },
      { code: "TT", name: "Trinidad and Tobago" },
      { code: "TN", name: "Tunisia" },
      { code: "TR", name: "Turkey" },
      { code: "TM", name: "Turkmenistan" },
      { code: "TC", name: "Turks and Caicos Islands" },
      { code: "TV", name: "Tuvalu" },
      { code: "UG", name: "Uganda" },
      { code: "UA", name: "Ukraine" },
      { code: "AE", name: "United Arab Emirates" },
      { code: "GB", name: "United Kingdom" },
      { code: "UM", name: "United States Minor Outlying Islands" },
      { code: "UY", name: "Uruguay" },
      { code: "US_UT", name: "Utah" },
      { code: "UZ", name: "Uzbekistan" },
      { code: "VU", name: "Vanuatu" },
      { code: "VE", name: "Venezuela" },
      { code: "US_VT", name: "Vermont" },
      { code: "VN", name: "Vietnam" },
      { code: "US_VA", name: "Virginia" },
      { code: "VG", name: "Virgin Islands, British" },
      { code: "VI", name: "Virgin Islands, United States " },
      { code: "WF", name: "Wallis and Futuna Islands" },
      { code: "US_WA", name: "Washington" },
      { code: "US_DC", name: "Washington, D.C." },
      { code: "EH", name: "Western Sahara" },
      { code: "US_WV", name: "West Virginia" },
      { code: "US_WI", name: "Wisconsin" },
      { code: "US_WY", name: "Wyoming" },
      { code: "YE", name: "Yemen" },
      { code: "ZM", name: "Zambia" },
      { code: "ZW", name: "Zimbabwe" },
    ],
    regulationNames: ["Common Principles", "CCPA"],
    rightsFulfilment: [
      {
        fulfillment: 45,
        rightCode: "cmn_delete",
        rightName: "Data Deletion",
      },
      { fulfillment: 45, rightCode: "cmn_access", rightName: "Data Access" },
      {
        fulfillment: 45,
        rightCode: "cmn_port",
        rightName: "Data Portability",
      },
      {
        fulfillment: 45,
        rightCode: "cmn_correction",
        rightName: "Data Correction",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_delete",
        rightName: "Right to Deletion (CCPA)",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_knowcollect",
        rightName: "Right to Disclosure of Information Collected",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_knowsold",
        rightName: "Right to Disclosure of Information Sold",
      },
    ],
  },
  {
    code: "hannahtest",
    name: "HannahTEST",
    regions: [{ code: "US_AL", name: "Alabama" }],
    regulationNames: ["Common Principles"],
    rightsFulfilment: [
      {
        fulfillment: 45,
        rightCode: "cmn_delete",
        rightName: "Data Deletion",
      },
      { fulfillment: 45, rightCode: "cmn_access", rightName: "Data Access" },
      {
        fulfillment: 45,
        rightCode: "cmn_port",
        rightName: "Data Portability",
      },
      {
        fulfillment: 45,
        rightCode: "cmn_correction",
        rightName: "Data Correction",
      },
    ],
  },
  {
    code: "jve_j_1",
    description: "downtown coolsville",
    name: "jve_j_1",
    regions: [{ code: "SD", name: "Sudan" }],
  },
  {
    code: "maine",
    name: "Maine",
    regions: [{ code: "US_ME", name: "Maine" }],
    regulationNames: ["Common Principles"],
    rightsFulfilment: [
      {
        fulfillment: 45,
        rightCode: "cmn_delete",
        rightName: "Data Deletion",
      },
      { fulfillment: 45, rightCode: "cmn_access", rightName: "Data Access" },
      {
        fulfillment: 45,
        rightCode: "cmn_port",
        rightName: "Data Portability",
      },
      {
        fulfillment: 45,
        rightCode: "cmn_correction",
        rightName: "Data Correction",
      },
    ],
  },
  {
    code: "testestest",
    name: "testestest",
    regions: [{ code: "US_CT", name: "Connecticut" }],
  },
  {
    code: "CA",
    description: "Covers California under CCPA and HIPAA",
    name: "US - California",
    regions: [{ code: "US_CA", name: "California" }],
    regulationNames: ["HIPAA", "CCPA"],
    rightsFulfilment: [
      {
        fulfillment: 60,
        rightCode: "hipaa_access",
        rightName: "Right of Access (HIPAA)",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_delete",
        rightName: "Right to Deletion (CCPA)",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_knowcollect",
        rightName: "Right to Disclosure of Information Collected",
      },
      {
        fulfillment: 90,
        rightCode: "ccpa_knowsold",
        rightName: "Right to Disclosure of Information Sold",
      },
    ],
  },
];
